const resumeData = {
  main: {
    name: "Chandni Anand",
    mobileNumber: "6393120563",
    profilepic:
      "https://media.licdn.com/dms/image/C4E03AQGHpWxUU2FYPQ/profile-displayphoto-shrink_800_800/0/1602072645079?e=2147483647&v=beta&t=Rd6i0EqWqqkbnixH1wY4wSDQTtjKTf2gTxCvrsvGjd8",
    description: "I'm a creative person driven by my passion for design.",
    bio: "Experienced Lead Graphic Designer with Ui/Ux skill a demonstrated history of working in the information technology, product management and services industry. Skilled in Management, Leadership, Project Management, User Experience Design (UED), and Customer Service. Strong arts and design professional Diploma from Arena Animation.",
    fullbio:
      "Experienced Lead Graphic Designer with Ui/Ux skill a demonstrated history of working in the information technology, product management and services industry. Skilled in Management, Leadership, Project Management, User Experience Design (UED), and Customer Service. Strong arts and design professional Diploma from Arena Animation.",
    contactmessage: "Get in touch with me together we can make changes.",
    email: "chandani.anand786@gmail.com",
    address: {
      street: "Mayur Residency Extension",
      city: "Lucknow",
      state: "Uttar Pradesh",
      country: "India",
      zip: "226016",
    },
    website: "www.thearpitanand.com",
  },
  portfolio: {
    webDesign: [
      {
        id: "0",
        shorttitle: "FOGG",
        title: "FOGG - Website",
        description: "",
        onFront: true,
        imageHeight: "300px",
        image: "/assets/images/webdesigs/fogg.jpeg",
        url: "https://www.figma.com/proto/GTSytPZC22FaUsXEhV0g2T/Fogg?node-id=1-14&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=1%3A237",
      },
      {
        id: "1",
        shorttitle: "Beardo",
        title: "Beardo - Web Application",
        description: "",
        onFront: true,
        imageHeight: "300px",
        image: "/assets/images/webdesigs/beardo.jpeg",
        url: "https://www.figma.com/proto/hn6DOIM23xGJgtB9DiMLM3/Beardo?node-id=1-119&starting-point-node-id=1%3A429",
      },
      {
        id: "2",
        shorttitle: "4700BC",
        title: "4700BC - Web Application",
        description: "",
        onFront: true,
        imageHeight: "300px",
        image: "/assets/images/webdesigs/4700BC.jpeg",
        url: "https://www.figma.com/proto/rVjHRX15O6usbb1ZBrZjOo/4700-bc?node-id=1-608&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=1%3A608",
      },
      {
        id: "3",
        shorttitle: "Chicago Vault",
        title: "Chicago Vault - Web Application",
        description: "",
        onFront: true,
        imageHeight: "300px",
        image: "/assets/images/webdesigs/chicago-valut.jpeg",
        url: "https://www.figma.com/proto/38IcbzJ3WLofRS55aqBF6Y/chicago?node-id=1-2",
      },
      {
        id: "4",
        shorttitle: "No Sympathy Card",
        title: "No Sympathy Card - Web Application",
        description: "",
        onFront: true,
        imageHeight: "300px",
        image: "/assets/images/webdesigs/no-sympathy-card.jpeg",
        url: "https://www.figma.com/proto/bZfwJMPSiGx6LQJwjhiEEs/ns-card?node-id=1-203",
      },
      {
        id: "5",
        shorttitle: "Fusion Fitness",
        title: "Fusion Fitness - Web Application",
        description: "",
        onFront: true,
        imageHeight: "300px",
        image: "/assets/images/webdesigs/fusion-fitness.jpeg",
        url: "https://www.figma.com/proto/jVQ2KKFltlSNO0L0jjuoXg/FItness-Fusion?node-id=389-2930&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=300%3A3033",
      },
      {
        id: "6",
        shorttitle: "H.S. JOHNSON",
        title: "H.S. JOHNSON - Web Application",
        description: "",
        onFront: true,
        imageHeight: "300px",
        image: "/assets/images/webdesigs/h-s-johnson.jpeg",
        url: "https://www.figma.com/proto/89dFNkh0dqJxfVXomkO9xs/HSJOHNSON(1946)?node-id=1-3&starting-point-node-id=1%3A3",
      },
    ],

    brandGuideline: [
      {
        id: "0",
        shorttitle: "CedCommerce-Branding-SM",
        title: "CedCommerce-Branding-SM - Guideline",
        description: "",
        onFront: true,
        imageHeight: "300px",
        image: "/assets/images/brand-guideline/CedCommerce-Branding-SM.jpeg",
        url: "https://drive.google.com/file/d/1so8QlNcfVLDfOIYmf4xImyfmTzkXE_Sl/view",
      },
      {
        id: "0",
        shorttitle: "Magenative Brand Guide Line",
        title: "Magenative Brand - Guideline",
        description: "",
        onFront: true,
        imageHeight: "300px",
        image: "/assets/images/brand-guideline/Magenative-Branding-SM.jpeg",
        url: "https://drive.google.com/file/d/1Mgl4tyhvmBVQv44I0HxS-RbFffQltxoP/view?usp=sharing",
      },
    ],

    presentation: [
      {
        id: "0",
        shorttitle: "Shop Talk 2022",
        title: "Shop Talk 2022",
        description: "",
        onFront: true,
        imageHeight: "300px",
        image: "/assets/images/presentations/shop-talk-2022.jpeg",
        url: "https://drive.google.com/file/d/1DSSWqWsiN565rHCn_oefCzRtR5_yHZVq/view?usp=sharing",
      },
      {
        id: "1",
        shorttitle: "Shop Talk 2023",
        title: "Shop Talk 2023",
        description: "",
        onFront: true,
        imageHeight: "300px",
        image: "/assets/images/presentations/shop-talk-2023.jpeg",
        url: "https://drive.google.com/file/d/1X4zwyQyp8ilB_37mjzaEqk_vzjPFzhlH/view?usp=sharing",
      },
      {
        id: "2",
        shorttitle: "Meet Magento",
        title: "Meet Magento",
        description: "",
        onFront: true,
        imageHeight: "300px",
        image: "/assets/images/presentations/meet-magento.jpeg",
        url: "https://drive.google.com/file/d/1vzZRZRFFAva3JXbzGuqfVpJMUO4gWiaS/view?usp=sharing",
      },
    ],
    logos: [
      {
        id: "0",
        shorttitle: "Amaziness",
        title: "Amaziness",
        description: "",
        onFront: true,
        imageHeight: "600px",
        image: "/assets/images/logo/amaziness.jpeg",
        url: "",
      },
      {
        id: "1",
        shorttitle: "Luvluxe",
        title: "Luvluxe",
        description: "",
        onFront: true,
        imageHeight: "600px",
        image: "/assets/images/logo/luvluxe.jpeg",
        url: "",
      },
      {
        id: "2",
        shorttitle: "Mastroke",
        title: "Mastroke",
        description: "",
        onFront: true,
        imageHeight: "600px",
        image: "/assets/images/logo/mastroke.jpeg",
        url: "",
      },
      {
        id: "3",
        shorttitle: "Mastroke - Sample",
        title: "Mastroke - Sample",
        description: "",
        onFront: true,
        imageHeight: "600px",
        image: "/assets/images/logo/mastroke-sample.jpeg",
        url: "",
      },
    ],
  },
};
export default resumeData;
