export const siteConfig = {
  url: "https://thearpitanand.com",
  title: "Arpit Anand",
  description:
    "Personal portfolio website of Arpit Anand, Senior Software Engineer and AI Enthusiast. Building AI products from 0 to 1 and scaling to billions.",
  ogImage: "https://thearpitanand.com/assets/og-images/ogimage.png",
  links: {
    github: "https://github.com/thearpitanand",
    linkedin: "https://www.linkedin.com/in/thearpitanand/",
    instagram: "https://www.instagram.com/anand_arpit/",
    twitterHandle: "@the_arpitanand",
  },
  author: "Arpit Anand",
  keywords: [
    "Arpit Anand",
    "Senior Software Engineer",
    "AI Enthusiast",
    "Building AI Products",
    "Scaling to Billions",
    "Software Development",
    "Python",
    "Machine Learning",
    "Deep Learning",
    "Computer Vision",
    "Natural Language Processing",
    "Generative AI",
    "LLMs",
    "Prompt Engineering",
    "RAG",
    "AI",
    "Frontend Development",
    "Backend Development",
    "Full Stack Development",
    "Software Development",
    "Software Engineer",
    "Software Developer",
    "Software Architect",
  ],
  jobTitle: "Senior Software Engineer",
  jobDescription:
    "AI Enthusiast | Building AI Products from 0 to 1 | Scaling to Billions",
  alumniOf: ["Veer Bahadur Singh Purvanchal University", "VBSPU"],
  knowsAbout: [
    "Software Development",
    "Python",
    "Machine Learning",
    "Deep Learning",
    "Computer Vision",
    "Natural Language Processing",
    "Generative AI",
    "LLMs",
    "Prompt Engineering",
    "RAG",
    "AI",
    "Frontend Development",
    "Next.js",
    "React",
    "TypeScript",
    "Node.js",
    "Express",
    "MongoDB",
    "PostgreSQL",
    "Docker",
    "Kubernetes",
    "TensorFlow",
    "PyTorch",
    "AWS",
    "CI/CD",
    "DevOps",
    "Cloud Computing",
    "Cloud Native",
    "Cloud Security",
    "Cloud Monitoring",
    "Cloud Automation",
    "Cloud Cost Optimization",
    "Cloud Performance Optimization",
  ],
};
